sudo: false

language: node_js
node_js:
  - 8

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build # make a dist folder

deploy:
  provider: npm
  email: jean.timex@gmail.com
  skip_cleanup: true
  api_key: 30c7c761-6dcf-46af-8a9e-4b211da2c4ed
  on:
    branch: master
    tags: true

branches:
  only:
    - master
